name: InfoPlugin
author: Nils Kevin Koerting-Eberhardt
version: 1.0-SNAPSHOT
main: de.nilskoeb.infoplugin.launcher.InfoPluginLauncher
commands:
  fly:
    aliases:
      - fliegen
    description: De-/ oder aktiviert den Flugmodus eines Spielers
    usage: /fly [Spieler]
    permission: infoplugin.command.fly
  gamemode:
    aliases:
      - gm
      - spielmodus
    description: Wechselt in den angegebenen Spielmodus
    usage: /gamemode <0,1,2,3> [Spieler]
    permission: infoplugin.command.gamemode
  schinken:
    description: Schenkt ein Stück Schinken
    usage: /schinken